// ---------------------------------------------------------------- //
//                                                                  //
//                 PLEASE DO NOT MODIFY THIS FILE.                  //
//               Hatchways automation depends on it.                //
//                                                                  //
// ---------------------------------------------------------------- //

import { THE_MOVIE_DB_API_BASE_URL } from "../env";
import { rest } from "msw";
const searchShowResponse = {
  page: 5,
  results: [
    {
      backdrop_path: "/cqwQQ5liJAUrV8HoL4Zs1CfXqyE.jpg",
      first_air_date: "2010-08-02",
      genre_ids: [10766, 18],
      id: 12926,
      name: "Teresa",
      origin_country: ["MX"],
      original_language: "es",
      original_name: "Teresa",
      overview:
        "Teresa Chavez is a young woman with an obsession for money and ambition. Despite her beauty and the fact that she was raised in the bosom of a loving family, she is resentful; her one desire is to leave her humble but poor neighbourhood.",
      popularity: 275.858,
      poster_path: "/17QQBTahkRE23bxJ4PmQ7tjMjyX.jpg",
      vote_average: 7.6,
      vote_count: 1556,
    },
    {
      backdrop_path: "/vJacVFr8Or0ddCYCb3ZU5vg3DeK.jpg",
      first_air_date: "2022-04-14",
      genre_ids: [10764],
      id: 154521,
      name: "The Kardashians",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Kardashians",
      overview:
        "The family you know and love is here with a brand new series, giving an all-access pass into their lives. Kris, Kourtney, Kim, Khloé, Kendall, and Kylie bring the cameras back to reveal the truth behind the headlines. From the intense pressures of running billion-dollar businesses to the hilarious joys of playtime and school drop-offs, this series brings viewers into the fold with a rivetingly honest story of love & life in the spotlight.",
      popularity: 272.675,
      poster_path: "/3cJgB4fOfgHKNoHgtT3h1Qqkvxq.jpg",
      vote_average: 8.9,
      vote_count: 973,
    },
    {
      backdrop_path: "/pnyT1foDmmXTsho2DfxN2ePI8ix.jpg",
      first_air_date: "2018-06-12",
      genre_ids: [18],
      id: 80240,
      name: "The Queen of Flow",
      origin_country: ["CO"],
      original_language: "es",
      original_name: "La Reina del Flow",
      overview:
        "After spending seventeen years in prison unfairly, a talented songwriter seeks revenge on the men who sank her and killed her family.",
      popularity: 280.5,
      poster_path: "/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg",
      vote_average: 8,
      vote_count: 1333,
    },
    {
      backdrop_path: "/zbBNp4djy9dGOfMzVBQoP1ZAdET.jpg",
      first_air_date: "2017-06-19",
      genre_ids: [35, 10751],
      id: 72637,
      name: "Once",
      origin_country: ["AR"],
      original_language: "es",
      original_name: "O11CE",
      overview:
        "The series revolves around Gabo, a soccer-loving teenager who, upon receiving a scholarship from the prestigious Sports Academic Institute (IAD) of Buenos Aires, will see his dream of playing at Los Halcones Dorados, the renowned amateur team of the school, and also his longing to become a professional footballer.",
      popularity: 272.884,
      poster_path: "/d4vPg3QsTJJh6C5MHARTb5CyqOu.jpg",
      vote_average: 8.7,
      vote_count: 1134,
    },
    {
      backdrop_path: "/wAAuhiwWqH42Xc3UZjDBUlGvk63.jpg",
      first_air_date: "2013-09-23",
      genre_ids: [18, 80, 9648],
      id: 46952,
      name: "The Blacklist",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Blacklist",
      overview:
        'Raymond "Red" Reddington, one of the FBI\'s most wanted fugitives, surrenders in person at FBI Headquarters in Washington, D.C. He claims that he and the FBI have the same interests: bringing down dangerous criminals and terrorists. In the last two decades, he\'s made a list of criminals and terrorists that matter the most but the FBI cannot find because it does not know they exist. Reddington calls this "The Blacklist". Reddington will co-operate, but insists that he will speak only to Elizabeth Keen, a rookie FBI profiler.',
      popularity: 269.897,
      poster_path: "/htJzeRcYI2ewMm4PTrg98UMXShe.jpg",
      vote_average: 7.6,
      vote_count: 2397,
    },
    {
      backdrop_path: "/6LFINpphlA8RvkxygndMWuhmeJe.jpg",
      first_air_date: "2022-07-05",
      genre_ids: [16, 35, 10765],
      id: 194774,
      name: "Vermeil in Gold",
      origin_country: ["JP"],
      original_language: "ja",
      original_name:
        "金装のヴェルメイユ~崖っぷち魔術師は最強の厄災と魔法世界を突き進む~",
      overview:
        'Royal Ortigia Magic Academy. Alto, on the verge of failing the summoning magic class and having to repeat the year, stumbles upon a grimoire and draws a magic circle, summoning the sealed demon Vermeil and making her his familiar. She has been a feared "devil" since ancient times and possesses tremendous power to cause disasters. Vermeil, as a familiar, necessitates magical energy on a daily basis, which she obtains from Alto via passionate kisses. Lilia, Alto\'s childhood friend, grows envious of their relationship, while the students are also taken aback by the unprecedented familiar. The royal road fantasy of a magician on the edge of failure and an unhealthy devil sister begins!',
      popularity: 252.955,
      poster_path: "/rZZShLsloFHk8RpfhfstZPMUVqZ.jpg",
      vote_average: 6.7,
      vote_count: 3,
    },
    {
      backdrop_path: "/k47JEUTQsSMN532HRg6RCzZKBdB.jpg",
      first_air_date: "2022-02-25",
      genre_ids: [10759, 18, 10768],
      id: 116135,
      name: "Vikings: Valhalla",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Vikings: Valhalla",
      overview:
        'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
      popularity: 250.199,
      poster_path: "/izIMqapegdEZj0YVDyFATPR8adh.jpg",
      vote_average: 8,
      vote_count: 260,
    },
    {
      backdrop_path: "/dfPDlU4G1QJ9ZzgwfZl60e1azVr.jpg",
      first_air_date: "2022-01-28",
      genre_ids: [18],
      id: 124902,
      name: "You Shall Not Lie",
      origin_country: ["ES"],
      original_language: "es",
      original_name: "Todos mienten",
      overview: "",
      popularity: 239.338,
      poster_path: "/66glWt0YL55LolAJgVvXSO95EvU.jpg",
      vote_average: 5.8,
      vote_count: 4,
    },
    {
      backdrop_path: "/e9n87p3Ax67spq3eUgLB6rjIEow.jpg",
      first_air_date: "2005-09-13",
      genre_ids: [80, 18],
      id: 1911,
      name: "Bones",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Bones",
      overview:
        "Dr. Temperance Brennan and her colleagues at the Jeffersonian's Medico-Legal Lab assist Special Agent Seeley Booth with murder investigations when the remains are so badly decomposed, burned or destroyed that the standard identification methods are useless.",
      popularity: 271.366,
      poster_path: "/eyTu5c8LniVciRZIOSHTvvkkgJa.jpg",
      vote_average: 8.3,
      vote_count: 2476,
    },
    {
      backdrop_path: "/z5EtkEDuIILoo3IrSi0FjZA9gVG.jpg",
      first_air_date: "2016-03-14",
      genre_ids: [10766, 10762],
      id: 66203,
      name: "Soy Luna",
      origin_country: ["AR"],
      original_language: "es",
      original_name: "Soy Luna",
      overview:
        "Although it is difficult for Luna to live in another country, she is determined to try everything to make new friends and achieve a new style of skating.",
      popularity: 262.311,
      poster_path: "/mK1egVq2qMLMw4HIREUXuihKj9g.jpg",
      vote_average: 7.9,
      vote_count: 931,
    },
    {
      backdrop_path: "/fZBu4qSOT2lmqu5sTNEwf3zZmbm.jpg",
      first_air_date: "2018-05-20",
      genre_ids: [10766, 18],
      id: 79699,
      name: "La hija del Mariachi",
      origin_country: ["CO"],
      original_language: "es",
      original_name: "La hija del Mariachi",
      overview: "",
      popularity: 262.488,
      poster_path: "/52jdBKWqtgl9qj6SFf7Z2H0qqvN.jpg",
      vote_average: 8,
      vote_count: 1222,
    },
    {
      backdrop_path: "/oAkpvVvoyZWMo9cpNk3aQoVKsjM.jpg",
      first_air_date: "2016-07-19",
      genre_ids: [10759, 80, 18, 9648],
      id: 67335,
      name: "Sin senos sí hay paraíso",
      origin_country: ["CO"],
      original_language: "es",
      original_name: "Sin senos sí hay paraíso",
      overview:
        "A young woman born in a mafia-controlled town seeks revenge on those who wrongfully harmed and imprisoned her family.",
      popularity: 243.868,
      poster_path: "/7lBJ6lOS0uQqsH13U9iMTikawQS.jpg",
      vote_average: 7.5,
      vote_count: 2576,
    },
    {
      backdrop_path: "/xio3AqrtsEERoVghgl8WWG0mXMu.jpg",
      first_air_date: "2022-04-24",
      genre_ids: [10765],
      id: 118663,
      name: "The Man Who Fell to Earth",
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Man Who Fell to Earth",
      overview:
        "An extraterrestrial alien arrives on Earth at a turning point in human evolution and must confront his own past to determine our future.",
      popularity: 225.141,
      poster_path: "/p1aBjGkyG25ADy4xu69joNMV3eQ.jpg",
      vote_average: 7.7,
      vote_count: 60,
    },
    {
      backdrop_path: "/uU6YW3N11qECNfz18LNGAGg3Uir.jpg",
      first_air_date: "2018-10-05",
      genre_ids: [80, 9648, 18],
      id: 76669,
      name: "Elite",
      origin_country: ["ES"],
      original_language: "es",
      original_name: "Élite",
      overview:
        "When three working class kids enroll in the most exclusive school in Spain, the clash between the wealthy and the poor students leads to tragedy.",
      popularity: 253.625,
      poster_path: "/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg",
      vote_average: 8.1,
      vote_count: 8238,
    },
    {
      backdrop_path: "/iQlel1ftOsnWguxyN98eUmKTOPm.jpg",
      first_air_date: "2021-07-28",
      genre_ids: [80, 10766],
      id: 128252,
      name: "The Snitch Cartel: Origins",
      origin_country: ["CO"],
      original_language: "es",
      original_name: "El cartel de los sapos: El origen",
      overview:
        "In Cali during the '60s and '70s, two brothers juggle family, romance and the joint pursuit of a burning ambition: to rule Colombia's drug industry.",
      popularity: 236.063,
      poster_path: "/A17Rt6BLHno0puR1QXbsSKhBfA4.jpg",
      vote_average: 7.8,
      vote_count: 260,
    },
    {
      backdrop_path: "/wFOKJucNqGSFh77KlV9fwxZNf6n.jpg",
      first_air_date: "2021-09-30",
      genre_ids: [16, 10759],
      id: 129600,
      name: "Baki Hanma",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "範馬刃牙",
      overview:
        "To gain the skills he needs to surpass his powerful father, Baki enters Arizona State Prison to take on the notorious inmate known as Mr. Unchained.",
      popularity: 242.668,
      poster_path: "/sQokxRU9AiT6nQmT4v19ys3Fim0.jpg",
      vote_average: 8,
      vote_count: 258,
    },
    {
      backdrop_path: "/yOtzSTFdccSd2tfzlTp8UNo2ZHN.jpg",
      first_air_date: "2022-04-20",
      genre_ids: [10766, 9648],
      id: 158916,
      name: "The Marked Heart",
      origin_country: ["CO"],
      original_language: "es",
      original_name: "Pálpito",
      overview:
        "This new Colombian telenovela is about a man who has to watch his wife die and have her heart extracted to give to another woman. He’s out for revenge in the world of organ trafficking.",
      popularity: 217.298,
      poster_path: "/M1q0HuyRnqxP8Si54srsPREFIH.jpg",
      vote_average: 8,
      vote_count: 100,
    },
    {
      backdrop_path: "/oycArCLGgtWyUz5aho7ojFZkgjN.jpg",
      first_air_date: "2002-10-03",
      genre_ids: [16, 10759, 10765],
      id: 46260,
      name: "Naruto",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "ナルト",
      overview:
        "In another world, ninja are the ultimate power, and in the Village Hidden in the Leaves live the stealthiest ninja in the land. Twelve years earlier, the fearsome Nine-Tailed Fox terrorized the village and claimed many lives before it was subdued and its spirit sealed within the body of a baby boy. That boy, Naruto Uzumaki, has grown up to become a ninja-in-training who's more interested in pranks than in studying ninjutsu.. but Naruto is determined to become the greatest ninja ever!",
      popularity: 245.519,
      poster_path: "/vauCEnR7CiyBDzRCeElKkCaXIYu.jpg",
      vote_average: 8.4,
      vote_count: 4600,
    },
    {
      backdrop_path: "/xJBT35KlQYSKmuSXu4D4DFmv3ka.jpg",
      first_air_date: "2010-09-24",
      genre_ids: [18, 80],
      id: 32692,
      name: "Blue Bloods",
      origin_country: ["US"],
      original_language: "en",
      original_name: "Blue Bloods",
      overview:
        "A drama about a multi-generational family of cops dedicated to New York City law enforcement. Frank Reagan is the New York Police Commissioner and heads both the police force and the Reagan brood. He runs his department as diplomatically as he runs his family, even when dealing with the politics that plagued his unapologetically bold father, Henry, during his stint as Chief.",
      popularity: 232.922,
      poster_path: "/nWYB1Pn3bNKQnTp4sWqyUxPTLI1.jpg",
      vote_average: 7.6,
      vote_count: 558,
    },
    {
      backdrop_path: "/qbxoEhlxNcyr7GjG2SXTShWn32m.jpg",
      first_air_date: "2018-06-26",
      genre_ids: [16, 10759, 80, 18],
      id: 80623,
      name: "BAKI",
      origin_country: ["JP"],
      original_language: "ja",
      original_name: "バキ",
      overview:
        "While martial arts champion Baki Hanma trains hard to surpass his legendary father, five violent death row inmates descend upon Tokyo to take him on.",
      popularity: 242.597,
      poster_path: "/c79L7zCnRzDJerrlbIWkNCjA6tg.jpg",
      vote_average: 8.2,
      vote_count: 1013,
    },
  ],
  total_pages: 6756,
  total_results: 135119,
};

const searchMovieResponse = {
  page: 5,
  results: [
    {
      adult: false,
      backdrop_path: "/ij6XoKnhieUQThY1wOjX7yLnUvw.jpg",
      genre_ids: [35],
      id: 933886,
      original_language: "es",
      original_title: "Dos más dos",
      overview: "",
      popularity: 415.407,
      poster_path: "/pcjTf0tBJoGwJQbdai4GmX8d1Om.jpg",
      release_date: "2022-03-31",
      title: "Dos más dos",
      video: false,
      vote_average: 6.9,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: "/i0zbSmiyyylh7H3Qb4jgscz46Pm.jpg",
      genre_ids: [27],
      id: 893370,
      original_language: "es",
      original_title: "Virus :32",
      overview:
        "A virus is unleashed and a chilling massacre runs through the streets of Montevideo.",
      popularity: 449.737,
      poster_path: "/qDNZWDJGU2LTPpPpVGPQMxKv8xl.jpg",
      release_date: "2022-04-21",
      title: "Virus:32",
      video: false,
      vote_average: 7.3,
      vote_count: 97,
    },
    {
      adult: false,
      backdrop_path: "/dW3fQJrshh2wYDoW4HUA7ZabsN1.jpg",
      genre_ids: [28, 53, 80],
      id: 763285,
      original_language: "en",
      original_title: "Ambulance",
      overview:
        "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
      popularity: 436.646,
      poster_path: "/zT5ynZ0UR6HFfWQSRf2uKtqCyWD.jpg",
      release_date: "2022-03-16",
      title: "Ambulance",
      video: false,
      vote_average: 6.9,
      vote_count: 914,
    },
    {
      adult: false,
      backdrop_path: "/svVppV4UOQw1fVi1Dt6z7n2UlyG.jpg",
      genre_ids: [35],
      id: 920143,
      original_language: "es",
      original_title: "El paseo 6",
      overview:
        "The last year High School excursion is the walk where anything can happen, but the last year High School excursion with the parents, that is the last straw. And since Álvaro Castaño knows that security is better than the police, he decides to travel with his family to watch over his daughter Sarita, however, his mother-in-law, Raquel, is not willing to allow it and also embarks in the plan . On the paradisiacal beaches of San Andrés, Álvaro Castaño will become Sara's nightmare and the sensation for the excursion, while his sexy mother-in-law of him will be the one to steal the show. El Paseo 6, the last yeat High School excursion, because the luck of the grandmother, the High School girls wish it.",
      popularity: 404.709,
      poster_path: "/5vSFW0rxMDZg8j5cr0JICBDSrGM.jpg",
      release_date: "2021-12-25",
      title: "The Trip 6",
      video: false,
      vote_average: 7.2,
      vote_count: 54,
    },
    {
      adult: false,
      backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
      genre_ids: [12, 28, 878],
      id: 299536,
      original_language: "en",
      original_title: "Avengers: Infinity War",
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      popularity: 452.275,
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      release_date: "2018-04-25",
      title: "Avengers: Infinity War",
      video: false,
      vote_average: 8.3,
      vote_count: 24917,
    },
    {
      adult: false,
      backdrop_path: "/ba3oFhz6DkzSjVXsr50AGRMkfh8.jpg",
      genre_ids: [35, 10749],
      id: 810171,
      original_language: "en",
      original_title: "The Valet",
      overview:
        "World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia’s new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.",
      popularity: 409.967,
      poster_path: "/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg",
      release_date: "2022-05-11",
      title: "The Valet",
      video: false,
      vote_average: 7.9,
      vote_count: 267,
    },
    {
      adult: false,
      backdrop_path: "/pxOiKwRvNp3zFOiuwpYpzlbmEgC.jpg",
      genre_ids: [16, 35, 12, 10751],
      id: 459151,
      original_language: "en",
      original_title: "The Boss Baby: Family Business",
      overview:
        "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
      popularity: 446.946,
      poster_path: "/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
      release_date: "2021-07-01",
      title: "The Boss Baby: Family Business",
      video: false,
      vote_average: 7.6,
      vote_count: 1980,
    },
    {
      adult: false,
      backdrop_path: "/pwH9kC1NSbFtkoD8Pd8wbm9zV5G.jpg",
      genre_ids: [16, 35, 10751],
      id: 952217,
      original_language: "en",
      original_title: "King Tweety",
      overview:
        "Everyone's favorite yellow canary unexpectedly becomes next in line for the crown when the queen of an island paradise disappears. His Little Highness’ entourage includes motorbike daredevil Granny and sly Sylvester, whose allegiance is tested when he uncovers a sinister plot to eliminate Tweety for good.",
      popularity: 525.901,
      poster_path: "/mGXWYbpakk8uX8OkW1ihPjVzapB.jpg",
      release_date: "2022-06-13",
      title: "King Tweety",
      video: false,
      vote_average: 7.6,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
      genre_ids: [27, 28, 878],
      id: 460458,
      original_language: "en",
      original_title: "Resident Evil: Welcome to Raccoon City",
      overview:
        "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
      popularity: 416.242,
      poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
      release_date: "2021-11-24",
      title: "Resident Evil: Welcome to Raccoon City",
      video: false,
      vote_average: 6.1,
      vote_count: 1697,
    },
    {
      adult: false,
      backdrop_path: "/jdLirLFnvSuAKin2XqZkwOEv4Km.jpg",
      genre_ids: [16, 28, 35],
      id: 913205,
      original_language: "en",
      original_title:
        "Teen Titans Go! & DC Super Hero Girls: Mayhem in the Multiverse",
      overview:
        "With the help of an ancient Kryptonian power, Lex Luthor unites the world’s Super-Villains to capture all of Earth's Super Heroes, until…only the DC Super Hero Girls are left to stop the Legion of Doom. Our heroes must cross dimensions to rescue their fellow Super Heroes from the Phantom Zone, but a fortuitous wrong turn leads them to Titans Tower – where they find much-needed allies in the Teen Titans!",
      popularity: 407.409,
      poster_path: "/3Hnhf1FqVGnh20hKlHbiRvHhB5b.jpg",
      release_date: "2022-05-23",
      title: "Teen Titans Go! & DC Super Hero Girls: Mayhem in the Multiverse",
      video: false,
      vote_average: 7.1,
      vote_count: 46,
    },
    {
      adult: false,
      backdrop_path: "/kIgfFzjjBNgx6Tr2LCw8Zkq921s.jpg",
      genre_ids: [28, 16, 878],
      id: 303857,
      original_language: "ja",
      original_title: "ドラゴンボールZ 復活の「F」",
      overview:
        "One peaceful day on Earth, two remnants of Frieza's army named Sorbet and Tagoma arrive searching for the Dragon Balls with the aim of reviving Frieza. They succeed, and Frieza subsequently seeks revenge on the Saiyans.",
      popularity: 444.096,
      poster_path: "/soq3AxjALdBfdPAm8H7yuMmNL5Y.jpg",
      release_date: "2015-04-18",
      title: "Dragon Ball Z: Resurrection 'F'",
      video: false,
      vote_average: 6.8,
      vote_count: 1412,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 831728,
      original_language: "de",
      original_title: "Willkommen in Siegheilkirchen",
      overview:
        "1960's Siegheilkirchen, a small town in the Austrian hinterland is steeped in reactionary and ultra-Catholic attitudes. The son of a hard-working innkeeper and his wife, called Snotty Boy by all and sundry, is at odds with the narrow-minded confines of his home town. But his unstoppable talent for drawing gives him an outlet for his discontent.",
      popularity: 442.759,
      poster_path: "/xvgmSslUbi416VwsW1C1Cp90yX.jpg",
      release_date: "2022-01-13",
      title: "Snotty Boy",
      video: false,
      vote_average: 5,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [14, 18],
      id: 770509,
      original_language: "es",
      original_title: "Las noches son de los monstruos",
      overview:
        "Sol, a 17-year-old teenager, moves with her mother to the Gonzalo's home, the actual mother's boyfriend. In this town, where from the beginning Sol only finds hostility, she must face bullying from her schoolmates and Gonzalo's harassment. While wandering the streets trying to find a way out, Sol meet a mysterious and magical female dog with whom she establish a symbiotic relationship. It be this dog, the one that violently and surprisingly, always appear to defend Sol until the last consequences.",
      popularity: 389.354,
      poster_path: "/cYNfI1WHxMm0JhCXEX9qUUOv8C3.jpg",
      release_date: "2021-10-09",
      title: "The Nights Belong to Monsters",
      video: false,
      vote_average: 6,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/zplzc6jxO3SK7Pa4yxVoRY5VflT.jpg",
      genre_ids: [14, 35, 12],
      id: 425909,
      original_language: "en",
      original_title: "Ghostbusters: Afterlife",
      overview:
        "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
      popularity: 399.335,
      poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
      release_date: "2021-11-11",
      title: "Ghostbusters: Afterlife",
      video: false,
      vote_average: 7.6,
      vote_count: 2949,
    },
    {
      adult: false,
      backdrop_path: "/2il2HT8v6NAN7oinOCuHKpEhgnB.jpg",
      genre_ids: [27, 53],
      id: 833425,
      original_language: "en",
      original_title: "No Exit",
      overview:
        "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.",
      popularity: 376.109,
      poster_path: "/5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg",
      release_date: "2022-02-25",
      title: "No Exit",
      video: false,
      vote_average: 6.9,
      vote_count: 600,
    },
    {
      adult: false,
      backdrop_path: "/znUdSyO9ZUopUfmr6DH5YT5D5Cs.jpg",
      genre_ids: [35, 10751],
      id: 892070,
      original_language: "es",
      original_title: "Padre no hay más que uno 3",
      overview:
        "Christmas is coming. The children accidentally break a Nativity scene figurine from their father's collection and must by all means get an equal one, the problem is that it is a unique antique piece. Sara, the eldest daughter breaks up with her boyfriend, Ocho, who will try to recover her favors with the help of her father-in-law, Javier. Precisely Javier's father-in-law, Marisa's father, will be welcomed into the family home to spend the holidays after her recent separation, which will not leave Javier's mother, Milagros, indifferent. Rocío, the folklore of the family, who has been playing the Virgin for several Christmases, is relegated this year to playing the shepherdess, something that her father, Javier, is not willing to assume.",
      popularity: 419.058,
      poster_path: "/sNbdbc0k0lin2U9OU4jO6lMRqlJ.jpg",
      release_date: "2022-07-15",
      title: "Padre no hay más que uno 3",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/eVSa4TpyXbOdk9fXSD6OcORJGtv.jpg",
      genre_ids: [53],
      id: 803114,
      original_language: "en",
      original_title: "The Requin",
      overview:
        "A couple on a romantic getaway find themselves stranded at sea when a tropical storm sweeps away their villa. In order to survive, they are forced to fight the elements, while sharks circle below.",
      popularity: 362.779,
      poster_path: "/i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg",
      release_date: "2022-01-28",
      title: "The Requin",
      video: false,
      vote_average: 4.6,
      vote_count: 147,
    },
    {
      adult: false,
      backdrop_path: "/c7xTZ9EA6GpH72xJC5s0x0KKR1a.jpg",
      genre_ids: [10751, 16, 12, 35],
      id: 211672,
      original_language: "en",
      original_title: "Minions",
      overview:
        "Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.",
      popularity: 338.212,
      poster_path: "/vlOgaxUiMOA8sPDG9n3VhQabnEi.jpg",
      release_date: "2015-06-17",
      title: "Minions",
      video: false,
      vote_average: 6.4,
      vote_count: 9347,
    },
    {
      adult: false,
      backdrop_path: "/t9K8ycUBCplWiICDOKRNRYcEH9e.jpg",
      genre_ids: [16, 28, 14],
      id: 810693,
      original_language: "ja",
      original_title: "劇場版 呪術廻戦 0",
      overview:
        "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
      popularity: 585.855,
      poster_path: "/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
      release_date: "2021-12-24",
      title: "Jujutsu Kaisen 0",
      video: false,
      vote_average: 7.9,
      vote_count: 213,
    },
    {
      adult: false,
      backdrop_path: "/zuOusg5xXMpzAXouktOGQICzkwb.jpg",
      genre_ids: [10751, 12],
      id: 955740,
      original_language: "en",
      original_title: "Dakota",
      overview:
        "Dakota, an ex-service dog, joins single mum Kate and her daughter Alex to live on their small-town family farm. Dakota quickly adjusts to her new home and becomes somewhat of a local hero, soon becoming inseparable from Alex. But when the farm’s existence is threatened by the town’s rogue sheriff, Dakota must help the family band together and save the land.",
      popularity: 431.243,
      poster_path: "/j3eUOPUoDwkupwTPTDk6ESqrzGt.jpg",
      release_date: "2022-04-01",
      title: "Dakota",
      video: false,
      vote_average: 5.8,
      vote_count: 8,
    },
  ],
  total_pages: 34302,
  total_results: 686037,
};

const getShowResponse = {
  backdrop_path: "/cqwQQ5liJAUrV8HoL4Zs1CfXqyE.jpg",
  first_air_date: "2010-08-02",
  genre_ids: [10766, 18],
  name: "Teresa",
  origin_country: ["MX"],
  original_language: "es",
  original_name: "Teresa",
  overview:
    "Teresa Chavez is a young woman with an obsession for money and ambition. Despite her beauty and the fact that she was raised in the bosom of a loving family, she is resentful; her one desire is to leave her humble but poor neighbourhood.",
  popularity: 275.858,
  poster_path: "/17QQBTahkRE23bxJ4PmQ7tjMjyX.jpg",
  vote_average: 7.6,
  vote_count: 1556,
};

const getMovieResponse = {
  adult: false,
  backdrop_path: "/ij6XoKnhieUQThY1wOjX7yLnUvw.jpg",
  genre_ids: [35],
  original_language: "es",
  original_title: "Dos más dos",
  overview: "",
  popularity: 415.407,
  poster_path: "/pcjTf0tBJoGwJQbdai4GmX8d1Om.jpg",
  release_date: "2022-03-31",
  title: "Dos más dos",
  video: false,
  vote_average: 6.9,
  vote_count: 20,
};

export const handlers = [
  rest.get(`${THE_MOVIE_DB_API_BASE_URL}/search/movie`, (req, res, ctx) => {
    return res(ctx.json(searchMovieResponse));
  }),
  rest.get(`${THE_MOVIE_DB_API_BASE_URL}/movie/:id`, (req, res, ctx) => {
    return res(
      ctx.json({
        id: typeof req.params.id === "string" ? parseInt(req.params.id) : 0,
        ...getMovieResponse,
      })
    );
  }),
  rest.get(`${THE_MOVIE_DB_API_BASE_URL}/search/tv`, (req, res, ctx) => {
    return res(ctx.json(searchShowResponse));
  }),
  rest.get(`${THE_MOVIE_DB_API_BASE_URL}/tv/:id`, (req, res, ctx) => {
    return res(
      ctx.json({
        id: typeof req.params.id === "string" ? parseInt(req.params.id) : 0,
        ...getShowResponse,
      })
    );
  }),
];
